### ISSUE TITLE
Error the Autonomous database connection failed for user: ADMIN  TNS service name: MY_ADW_low java.sql.SQLRecoverableException: Listener refused the connection with the following error: ORA-12514, TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by jmleandrocr** [oracle/adb-free#11]
podman run -p 1521:1522 -p 1522:1522 -p 8443:8443 -p 27017:27017 -e WORKLOAD_TYPE='ADW' -e WALLET_PASSWORD=Oracle*123 -e ADMIN_PASSWORD=Welcome_MY_ATP_1234 --cap-add SYS_ADMIN --device /dev/fuse --name adb_free --volume adb_container_volume:/u01/data ghcr.io/oracle/adb-free:latest
Archive:  /u01/POD1.zip
   creating: /u01/app/oracle/oradata/
   creating: /u01/app/oracle/oradata/POD1/
   creating: /u01/app/oracle/oradata/POD1/0A156A2AE0DA39A7E06377234664C7E0/
   creating: /u01/app/oracle/oradata/POD1/0A156A2AE0DA39A7E06377234664C7E0/datafile/
  inflating: /u01/app/oracle/oradata/POD1/0A156A2AE0DA39A7E06377234664C7E0/datafile/o1_mf_temp_lsccovmr_.tmp
   creating: /u01/app/oracle/oradata/POD1/0A1438F87F472D38E0637723466488D2/
   creating: /u01/app/oracle/oradata/POD1/0A1438F87F472D38E0637723466488D2/datafile/
  inflating: /u01/app/oracle/oradata/POD1/0A1438F87F472D38E0637723466488D2/datafile/o1_mf_temp_lsccory9_.tmp
  inflating: /u01/app/oracle/oradata/POD1/redo01.log
  inflating: /u01/app/oracle/oradata/POD1/redo02.log
   creating: /u01/app/oracle/oradata/POD1/datafile/
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_undotbs1_lscfo0to_.dbf
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_temp_lscfo2no_.tmp
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_temp_lsccondj_.tmp
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_system_lsccg3w1_.dbf
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_sysaux_lsccg3wz_.dbf
  inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_data_lsccg3y1_.dbf
   creating: /u01/app/oracle/oradata/POD1/0E10A174E5A0408DE0636402000A759D/
   creating: /u01/app/oracle/oradata/POD1/0E10A174E5A0408DE0636402000A759D/datafile/
   creating: /u01/app/oracle/oradata/POD1/onlinelog/
   creating: /u01/app/oracle/oradata/POD1/0E1099BA25FC3D75E0636402000ADF30/
   creating: /u01/app/oracle/oradata/POD1/0E1099BA25FC3D75E0636402000ADF30/datafile/
   creating: /u01/app/oracle/oradata/POD1/0E10A7FCACD24110E0636402000AF7B6/
   creating: /u01/app/oracle/oradata/POD1/0E10A7FCACD24110E0636402000AF7B6/datafile/
   creating: /u01/app/oracle/oradata/POD1/controlfile/
  inflating: /u01/app/oracle/oradata/POD1/controlfile/o1_mf_lscctrtj_.ctl
TIME ELAPSED Unzipping /u01/POD1.zip: 0 minutes and 50 seconds elapsed
User input JSON not found
MY ADB WORKLOAD_TYPE is ADW
MY ADB CUSTOM NAME is MY_ADW
BUILDER: Configuring TCPS
BUILDER: Cleanup /u01/app/oracle/wallets/tls_wallet
BUILDER: Creating auto login wallet for server
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Enter password:
Enter password again:
Operation is successfully completed.
BUILDER: Creating a self-signed certificate using orapki utility; VALIDITY: 10 years
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Cannot modify auto-login (sso) wallet
Enter wallet password:
Operation is successfully completed.
BUILDER: exporting server's cert
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Operation is successfully completed.
BUILDER: exporting server's cert
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Operation is successfully completed.
BUILDER: exporting encrypted private key
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Private key password:
Enter password:
Enter password again:
Enter wallet password:
BUILDER: exporting private and certificates together in PEM
BUILDER: generating keystore.jks and truststore.jks
Oracle PKI Tool Release 19.0.0.0.0 - Production
Version PT.DBCLOUD19
Copyright (c) 2004, 2023, Oracle and/or its affiliates. All rights reserved.

Enter wallet password:
Enter Key store password:
Enter Trust store password:
Operation is successfully completed.
Operation is successfully completed.
BUILDER: generating sqlnet.ora for client
BUILDER: Generating  tnsnames.ora based on the new CN
BUILDER: Overriding service names based on user input
BUILDER: generating ojdbc.properties
BUILDER: zipping wallet for ORDS
updating: README (stored 0%)
updating: adb_container.cert (deflated 24%)
updating: cwallet.sso (stored 0%)
updating: cwallet.sso.lck (stored 0%)
updating: ewallet.p12 (stored 0%)
updating: ewallet.p12.lck (stored 0%)
updating: ewallet.pem (deflated 25%)
updating: keystore.jks (stored 0%)
updating: ojdbc.properties (deflated 49%)
updating: sqlnet.ora (deflated 16%)
updating: tnsnames.ora (deflated 83%)
updating: truststore.jks (deflated 5%)
TIME ELAPSED Wallet Generation: 0 minutes and 18 seconds elapsed
User has requested to download '.pdb' archive file from Object Storage bucket
MY_ADW.pdb already exists
TIME ELAPSED Downloaded PDBs: 0 minutes and 0 seconds elapsed

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 24-JAN-2024 17:23:11

Copyright (c) 1991, 2023, Oracle.  All rights reserved.

Starting /u01/app/oracle/product/19.0.0.0/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /u01/app/oracle/product/19.0.0.0/dbhome_1/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/dd2c45d1b8fa/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)(FIREWALL=OFF)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=0.0.0.0)(PORT=1522)(FIREWALL=OFF)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=0.0.0.0)(PORT=1521)(FIREWALL=OFF)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                24-JAN-2024 17:23:12
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/19.0.0.0/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/dd2c45d1b8fa/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)(FIREWALL=OFF)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=0.0.0.0)(PORT=1522)(FIREWALL=OFF)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
The listener supports no services
The command completed successfully
TIME ELAPSED Listener started: 0 minutes and 1 seconds elapsed

SQL*Plus: Release 19.0.0.0.0 - Production on Wed Jan 24 17:23:12 2024
Version 19.21.0.1.0

Copyright (c) 1982, 2023, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORACLE instance started.

Total System Global Area 1610612720 bytes
Fixed Size                  9543664 bytes
Variable Size             385875968 bytes
Database Buffers         1207959552 bytes
Redo Buffers                7233536 bytes
Database mounted.
Database opened.
SQL> Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.21.0.1.0
TIME ELAPSED Database started: 1 minutes and 1 seconds elapsed
/u01/data/plug_my_container_pdb_20240124_161743.log :
Creating PDB: MY_ADW
Opened PDB in read write mode: MY_ADW

Successfully plugged

TIME ELAPSED to plug MY_ADW: 0 minutes and 0 seconds elapsed
Error DPY-6005: cannot connect to database (CONNECTION_ID=AF9HvYhoJbNWQDs6B3xuJA==).
DPY-6001: Service "my_adw" is not registered with the listener at host "localhost" port 1521. (Similar to ORA-12514) changing password for MY_ADW user admin
TIME ELAPSED Changed password: 0 minutes and 1 seconds elapsed
BUILDER: Getting custom DB name
BUILDER: Installing ORDS for MY_ADW

ORDS: Release 23.4 Production on Wed Jan 24 17:24:36 2024

Copyright (c) 2010, 2024, Oracle.

Configuration:
  /u01/ords/

Oracle REST Data Services - Non-Interactive Customer Managed ORDS for Autonomous Database
Error the Autonomous database connection failed for user: ADMIN  TNS service name: MY_ADW_low
java.sql.SQLRecoverableException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
  (CONNECTION_ID=2SeRebJoTYSsdq7R/XK5vg==)

**Comment by jmleandrocr** [comment]
I'm getting this error when I run it more than once time using persistent volumen

**Comment by aosingh** [comment]
@jmleandrocr 

Do you `rm` the container in between every run command ? If you want to just retain the container data you can simply do a start/stop. 

`podman stop adb-free`
`podman start adb-free`

I think, I know the cause of the problem reported in this issue. It is because of a file `MY_ADW.plugged` in the persistent volume. 

While we fix this, there are 2 workarounds:

1. If you don't wish to move data across containers you can get rid of the `--volume` option in podman run command

2. Or In between podman run commands, you could automate to do the following
```
podman inspect adb_container_volume

cd <mountpoint>

sudo rm -rf MY_ADW.plugged 
```

**Comment by aosingh** [comment]
@jmleandrocr 

Please test the latest released image version. This is fixed.

```
docker pull ghcr.io/oracle/adb-free:23.10.2.4
```

**Comment by alexesca** [comment]
Can this be closed?
