### ISSUE TITLE
Keep the latest version of ORACLE APEX & ORDS in sync

### ISSUE THREAD

**Issue by alexesca** [oracle/adb-free#13]
This version of APEX is out of date. I need this image to keep up with the latest version of APEX on OCI. The latest version of ORACLE APEX in OCI at this moment is 23.2.4

**Comment by spanchum** [comment]
Any specific feature you need from newer version of APEX. Free container image may be few months behind what;s in the ADB-S cloud. If you need the latest APEX, using ADB free in the cloud may be another option. What's blocking with container image being on lower version. You can still export and import app to Cloud, right?

**Comment by alexesca** [comment]
@spanchum I cannot import things from the cloud into the adb-free's APEX lower version. I need to be on the same patch release to be able to develop locally, commit to git, and then push to the cloud, and repeat the process. We have a big team and we move fast. I want the development lifecycle to be fast and simple. I was able to apply my db's schema's objects into this version of 19c. The only thing I need, is for it to be on the latest patch release of APEX. It could be a huge productivity game changer with little effort.

**Comment by alexesca** [comment]
@spanchum. Do you know when this image will be updated to 23.2? This docker image is exactly what we need. I understand "Current model is mainly to develop app in container and exporting to cloud". The thing is that I found this image a few months after I started developing the app on the cloud. We need some new components from 23.2, so that is why we are on 23.2. I tried the other oracle container registry images, but it is impossible to get the same setup.  This image is vital for our development!

**Comment by alexesca** [comment]
@aosingh 23.2 is a big growth driver for apex. All of the new OCI/APEX developers will start out using APEX 23.2. It makes sense for ORACLE to upgrade this image, so new developers in enterprise teams can develop!

**Comment by spanchum** [comment]
Hi @alexesca  We are working a next version of the image. We expect to publish in 3-4 weeks.

**Comment by alexesca** [comment]
@spanchum @aosingh how is the next version of the image going? I really need it. I have been developing on 23c, but deploying on 19c and we are running into issues that are hard to fix. Please, let me know as soon as you push the image!

**Comment by spanchum** [comment]
We are close to getting it out. Will keep you posted

**Comment by aosingh** [comment]
@alexesca 

We have pushed the next version of adb-free image

```
docker pull ghcr.io/oracle/adb-free:24.3.2.1
```

Please check the updated [documentation](https://github.com/oracle/adb-free/pkgs/container/adb-free)
