### ISSUE TITLE
Running sdb-free with Rosetta and platform as amd64 failing with given error

### ISSUE THREAD

**Issue by cvasani** [oracle/adb-free#19]
Error
```tex
ORA-03113: end-of-file on communication channel
```
And then
```tex
CTimeout: Database could not be plugged in 380.0s
Traceback (most recent call last):
  File "/u01/scripts/wait_for_database_to_be_plugged.py", line 81, in <module>
    wait_until_plugged(pdb_name=args.pdb_name, timeout_in_seconds=float(args.timeout))
  File "/u01/scripts/wait_for_database_to_be_plugged.py", line 58, in wait_until_plugged
    raise MyContainerPDBPlugTimeoutError(f"Could not plugin pdb {pdb_name} in {timeout_in_seconds}s")
__main__.MyContainerPDBPlugTimeoutError: Could not plugin pdb MYADW in 380.0s
Stopping container.
SIGINT received, shutting down database!
```

**Comment by aosingh** [comment]
@cvasani 

Could you share the container start command ? 

And are you using colima or Docker Desktop for MacOS ?

**Comment by aosingh** [comment]
Also, confirming if you have started the colima VM [as documented in F.A.Q](https://github.com/oracle/adb-free?tab=readme-ov-file#how-can-i-start-colima-x86_64-virtual-machine-using-apples-new-virtualization-framework---rosetta-)

**Comment by cvasani** [comment]
Using Colima with Rosetta with arm64 archiecture.
I am not using given command to create instance. Could you please take this as PR if possible as the virtualization on M2/M3 is very slow compare.

**Comment by aosingh** [comment]
> I am not using given command to create instance.

May I know the sequence of commands you ran If I have to reproduce this error ?

**Comment by cvasani** [comment]
its seems Rosetta with Vz is not working. we need to use x86 arch for usage and the moment we use colima with x86 it uses Qemu and that is considerably slow. 

Thanks for help. I am closing this issue now .
