### ISSUE TITLE
Does adb-free have the DBMS_CLOUD package preinstalled?

### ISSUE THREAD

**Issue by alexesca** [oracle/adb-free#27]
I need to be able to enable printing using the OCI cloud function and DBMS_CLOUD is a requirement.  

[Install DBMS_CLOUD](https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_CLOUD.html#GUID-BCE328FA-F949-4C66-A82F-0956E50C314E)

Please let me know if this package has it or if you are planning to offer the image with it preinstalled

Thanks!

**Comment by aosingh** [comment]
@alexesca 

DBMS_CLOUD is already available in the container.

**Comment by aosingh** [comment]
@alexesca 

Any package which is available in Autonomous Database in Cloud is installed in the ADB Container image too.
