### ISSUE TITLE
Archive Log Mode does not appear to default to true

### ISSUE THREAD

**Issue by spooky2k2-uk** [oracle/adb-free#34]
Docs say ENABLE_ARCHIVE_LOG parameter will default to true, but archive log mode for an ATP without setting the parameter shows log_mode as NOARCHIVELOG from v$database.

**Comment by aosingh** [comment]
@spooky2k2-uk 

Which image and database version are you using ?  

Also, could you please share the container start command and container logs ?

```
podman logs <container_id>
```

**Comment by aosingh** [comment]
@spooky2k2-uk 

The container-registry 23ai adb-free image is old. It corresponds to version 24.4.4.2 released in April. 

We have released a new version of 23ai adb-free image just yesterday on Oracle Github registry. Please try with it

```bash
docker pull ghcr.io/oracle/adb-free:latest-23ai
```

You should see the expected value of `log_mode`

```sql
Oracle Database 23ai Enterprise Edition Release 23.0.0.0.0 - Production
Version 23.6.0.24.11

SQL> set markup csv on
SQL> select log_mode from v$database;
"LOG_MODE"
"ARCHIVELOG"


```

We are updating Oracle Container Registry mirror (container-registry.oracle.com) too and the latest 23ai image should be there tonight.

**Comment by spooky2k2-uk** [comment]
ah ok, I did get the older version working with archive log enabled, though it was not the default. 

I will try the latest version via ghcr.io. 

* Have tried it and see that it does indeed default to archive log mode. Thanks for the updates.
